services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports: 
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env

volumes:
  wordpress_volume:
  mariadb_volume: