services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports: 
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    restart: on-failure

volumes:
  wordpress_volume:
  mariadb_volume:

networks:
  inception_network:
    driver: bridge